apiVersion: apps/v1
kind: DaemonSet
metadata:
   name: no2-ds
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.12
        ports:
          - containerPort: 80