apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: no4-job
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 30
  suspend: false
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: output-date
            image: alpine:latest
            command:
            - "date"
          restartPolicy: Never