apiVersion: v1
kind: Pod
metadata:
  name: cache
spec:
  containers:
    - name: redis-container
      image: redis:5.0
      ports:
      - containerPort: 6379
      resources:
        limits:
          cpu: 100m
          memory: 32Mi
        requests:
          cpu: 10m
          memory: 8Mi