apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
          - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wp-configmap
              key: wp-db-host
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: wp-configmap
              key: wp-db-user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-db-auth
              key: password